
import React, { useState, useEffect } from 'react';
import { 
  FileText, Workflow, BookOpen, ScrollText, MessageSquare, Bot, Activity, Briefcase
} from 'lucide-react';
import { useAuth, useSettings, useNavigation } from '../contexts';
import { ModuleData } from '../types';
import { AVAILABLE_UI_COMPONENTS } from '../constants';
import { api } from '../client';

// Sub-components
import { RequirementsTab } from './feature-studio/RequirementsTab';
import { KnowledgeTab } from './feature-studio/KnowledgeTab';
import { CommentsTab } from './feature-studio/CommentsTab';
import { AIPromptModal } from './feature-studio/AIPromptModal';
import { AIAssistantTab } from './feature-studio/AIAssistantTab';
import { StatusTab } from './feature-studio/StatusTab';
import { BusinessReqTab } from './feature-studio/BusinessReqTab';
import { ArchitectureTab } from './feature-studio/ArchitectureTab';
import { ImplementationTab } from './feature-studio/ImplementationTab';
import { FeatureGeneratorModal, GeneratedData } from './feature-studio/FeatureGeneratorModal';

interface FeatureStudioProps {
  moduleId: string;
  moduleName: string;
}

type Tab = 'status' | 'expert_req' | 'ai_assistant' | 'req' | 'architecture' | 'implementation' | 'knowledge' | 'comments';

export const FeatureStudio: React.FC<FeatureStudioProps> = ({ moduleId, moduleName }) => {
  const { user } = useAuth();
  const { globalStandards } = useNavigation();
  const { language } = useSettings();
  
  const [activeTab, setActiveTab] = useState<Tab>('status'); 
  const [showPromptModal, setShowPromptModal] = useState(false);
  const [showGeneratorModal, setShowGeneratorModal] = useState(false);

  // Local State representing the Module Data
  // Initialize with empty default to be populated by useEffect
  const [data, setData] = useState<ModuleData>({
    id: moduleId,
    name: moduleName,
    status: 'draft',
    owners: { pm: [], dev: [], expert: [] },
    timeline: { startDate: '', endDate: '' },
    requirements: '',
    expertRequirements: '',
    logicRules: [],
    knowledge: [],
    uiComponents: [],
    figmaLinks: [],
    prototypeImages: [],
    comments: [],
    versions: [],
    updatedAt: new Date().toISOString(),
  });

  // Fetch/Reset data when module changes
  useEffect(() => {
    setShowPromptModal(false);
    setShowGeneratorModal(false);
    const fetchData = async () => {
      try {
        const remoteData = await api.modules.get(moduleId);
        
        const baseData: ModuleData = {
          id: moduleId,
          name: moduleName,
          status: 'draft',
          owners: { pm: [], dev: [], expert: [] },
          timeline: { startDate: '', endDate: '' },
          requirements: '',
          expertRequirements: '',
          logicRules: [],
          knowledge: [],
          uiComponents: AVAILABLE_UI_COMPONENTS.map(c => ({...c, checked: false})),
          figmaLinks: [],
          prototypeImages: [],
          comments: [],
          versions: [],
          updatedAt: new Date().toISOString(),
        };

        if (remoteData && Object.keys(remoteData).length > 0) {
           // Merge remote data with base structure to ensure all fields exist
           setData({
               ...baseData,
               ...remoteData,
               id: moduleId,
               name: moduleName
           });
        } else {
           // Fallback / New Module Template
           const genericTemplate = `### 1. Overview\nScope definition for **${moduleName}**.\n\n> *Content generated by AI Assistant placeholder.*\n\n---\n### 2. Core Features\n- [ ] Feature 1: Basic CRUD operations.\n- [ ] Feature 2: Search and filtering.\n- [ ] Feature 3: Status workflow transition.\n\n---\n### 3. Data Model\n| Field | Type | Description |\n| :--- | :--- | :--- |\n| \`id\` | UUID | Primary Key |\n| \`name\` | String | Name or Title |\n| \`status\` | Enum | Lifecycle Status |\n| \`created_at\` | DateTime | Creation Timestamp |`;
           
           const initialData = {
               ...baseData,
               requirements: genericTemplate
           };
           setData(initialData);
        }
      } catch (error) {
          console.error("Failed to fetch module data:", error);
      }
    };

    fetchData();
  }, [moduleId, moduleName]);

  const updateData = (updates: Partial<ModuleData>) => {
    setData(prev => {
        const newData = { ...prev, ...updates, updatedAt: new Date().toISOString() };
        // Sync with backend
        api.modules.update(moduleId, newData).catch(console.error);
        return newData;
    });
  };

  const handleApplyAIContent = (content: string) => {
    // Append to existing requirements
    const newRequirements = data.requirements + "\n\n" + content;
    updateData({ requirements: newRequirements });
    setActiveTab('req'); // Switch to req tab to see changes
  };

  const handleGeneratorComplete = (results: GeneratedData) => {
    // 1. Update Requirements (PRD Only)
    // The PRD should go to the "Requirements PRD" tab content.
    // In our data model, `requirements` field holds this.
    // We replace or append. Let's append with a clear separator if not empty.
    const prdContent = results.prd;
    const newRequirements = data.requirements ? data.requirements + "\n\n---\n\n" + prdContent : prdContent;
    
    // 2. Update Knowledge (Architecture) -> "Tech Architecture" Tab
    // We store this as a Knowledge entry tagged 'architecture'
    const archEntry = {
        id: Date.now().toString(),
        title: 'Technical Architecture',
        type: 'doc' as const,
        content: results.architecture,
        tags: ['auto-generated', 'architecture'],
        updatedAt: new Date().toISOString()
    };

    // 3. Update Tasks -> "Implementation Tasks" Tab
    // We store this as a Knowledge entry tagged 'tasks' (or 'implementation')
    // Formatting the tasks JSON into a readable Markdown list for display
    const tasksContent = results.tasks.map((t: any) => `- [ ] **${t.title}** (${t.type}) - ${t.priority}`).join('\n');
    const tasksEntry = {
        id: (Date.now() + 1).toString(),
        title: 'Implementation Plan',
        type: 'doc' as const,
        content: tasksContent,
        tags: ['auto-generated', 'tasks'],
        updatedAt: new Date().toISOString()
    };

    // Update State
    // Note: We are NOT appending tasks to `requirements` field anymore, 
    // keeping PRD pure in 'requirements' field.
    // Tasks live in knowledge base now, visualized in Implementation Tab.
    
    updateData({
        requirements: newRequirements,
        knowledge: [...data.knowledge, archEntry, tasksEntry]
    });
    
    setActiveTab('architecture'); // Switch to Architecture tab
  };

  const t = (key: string) => {
    const dict: Record<string, { en: string; zh: string }> = {
      'status': { en: 'Function Status', zh: '功能状态' },
      'expert_req': { en: 'Business Req', zh: '业务需求' },
      'ai_assistant': { en: 'AI Assistant', zh: 'AI 助理' },
      'req': { en: 'Requirements PRD', zh: '需求 PRD' },
      'architecture': { en: 'Tech Architecture', zh: '技术架构' },
      'implementation': { en: 'Implementation Tasks', zh: '实施任务' },
      'knowledge': { en: 'Knowledge', zh: '知识库' },
      'comments': { en: 'Discussion', zh: '讨论区' },
      'ai_bridge': { en: 'AI Bridge', zh: 'AI 桥接' },
    };
    return dict[key] ? dict[key][language] : key;
  };

  return (
    <div className="flex flex-col h-full bg-white dark:bg-slate-900 transition-colors">
        {/* Top Bar with Tabs */}
        <div className="flex items-center justify-between px-6 py-3 border-b border-gray-200 dark:border-gray-800 shrink-0">
             <div className="flex items-center gap-1 bg-gray-100 dark:bg-slate-800 p-1 rounded-lg overflow-x-auto custom-scrollbar">
                {(['status', 'expert_req', 'ai_assistant', 'req', 'architecture', 'implementation', 'knowledge', 'comments'] as Tab[]).map((tab) => (
                    <button
                        key={tab}
                        onClick={() => setActiveTab(tab)}
                        className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-medium transition-all whitespace-nowrap
                            ${activeTab === tab 
                                ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-400 shadow-sm' 
                                : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'
                            }`}
                    >
                        {tab === 'status' && <Activity size={14} />}
                        {tab === 'expert_req' && <Briefcase size={14} />}
                        {tab === 'ai_assistant' && <Bot size={14} />}
                        {tab === 'req' && <FileText size={14} />}
                        {tab === 'architecture' && <Workflow size={14} />}
                        {tab === 'implementation' && <ScrollText size={14} />}
                        {tab === 'knowledge' && <BookOpen size={14} />}
                        {tab === 'comments' && <MessageSquare size={14} />}
                        {t(tab)}
                    </button>
                ))}
             </div>

             <div className="flex items-center gap-2">
                 {/* Auto Architect Button */}
                 <button 
                    onClick={() => setShowGeneratorModal(true)}
                    className="flex items-center gap-2 bg-gradient-to-r from-emerald-500 to-teal-600 text-white px-3 py-1.5 rounded-lg hover:shadow-lg hover:opacity-90 transition-all text-xs font-medium whitespace-nowrap"
                 >
                    <Bot size={16} />
                    <span>Auto-Architect</span>
                 </button>

                 {/* AI Bridge Button */}
                 <button 
                    onClick={() => setShowPromptModal(true)}
                    className="flex items-center gap-2 bg-gradient-to-r from-indigo-600 to-violet-600 text-white px-3 py-1.5 rounded-lg hover:shadow-lg hover:opacity-90 transition-all text-xs font-medium whitespace-nowrap"
                 >
                    <Bot size={16} />
                    <span>{t('ai_bridge')}</span>
                 </button>
             </div>
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-hidden p-3 bg-gray-50 dark:bg-black/20">
             <div className="h-full bg-white dark:bg-slate-900 rounded-xl border border-gray-200 dark:border-gray-800 shadow-sm overflow-hidden min-h-0 flex flex-col">
                <div className="flex-1 min-h-0 p-4 overflow-hidden">
                {activeTab === 'status' && (
                    <StatusTab data={data} onUpdate={updateData} />
                )}
                {activeTab === 'expert_req' && (
                    <BusinessReqTab moduleId={moduleId} moduleName={moduleName} />
                )}
                {activeTab === 'ai_assistant' && (
                    <AIAssistantTab 
                        moduleId={moduleId} 
                        moduleName={moduleName}
                        onApplyToRequirements={handleApplyAIContent}
                    />
                )}
                {activeTab === 'req' && (
                    <RequirementsTab data={data} onUpdate={updateData} />
                )}
                {activeTab === 'knowledge' && (
                    <KnowledgeTab data={data} onUpdate={updateData} />
                )}
                {activeTab === 'architecture' && (
                    <ArchitectureTab data={data} onUpdate={updateData} />
                )}
                
                {activeTab === 'implementation' && (
                     <ImplementationTab data={data} onUpdate={updateData} />
                )}
                {activeTab === 'comments' && (
                    <CommentsTab moduleId={moduleId} moduleName={moduleName} />
                )}
                </div>
             </div>
        </div>

        {/* AI Prompt Modal */}
        <AIPromptModal 
            isOpen={showPromptModal}
            onClose={() => setShowPromptModal(false)}
            data={data}
            user={user}
            globalStandards={globalStandards}
        />

        {/* Feature Generator Modal */}
        <FeatureGeneratorModal 
            isOpen={showGeneratorModal}
            onClose={() => setShowGeneratorModal(false)}
            onComplete={handleGeneratorComplete}
        />
    </div>
  );
};
